### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant com.huawei.hms.scankit.p.cy.c

### ISSUE THREAD

**Issue by nukc** [HMS-Core/hms-scan-demo#11]
R8编译
```java
java.lang.RuntimeException: Unable to resume activity {com.xx/com.huawei.hms.hmsscankit.ScanKitActivity}: java.lang.IllegalArgumentException: No enum constant com.huawei.hms.scankit.p.cy.c
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4008)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4040)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.IllegalArgumentException: No enum constant com.huawei.hms.scankit.p.cy.c
        at java.lang.Enum.valueOf(Enum.java:258)
        at com.huawei.hms.scankit.p.cy.valueOf(FrontLightMode.java:1)
        at com.huawei.hms.scankit.p.cy.a(FrontLightMode.java:1)
        at com.huawei.hms.scankit.p.cy.a(FrontLightMode.java:2)
        at com.huawei.hms.scankit.a.a(AmbientLightManager.java:3)
        at com.huawei.hms.scankit.c.c(CaptureHelper.java:8)
        at com.huawei.hms.scankit.m.onResume(IRemoteViewDelegateImpl.java:1)
        at com.huawei.hms.hmsscankit.RemoteView$b.onResume(RemoteView.java:1)
        at com.huawei.hms.feature.dynamic.DeferredLifecycleHelper$6.a(Unknown Source:9)
        at com.huawei.hms.feature.dynamic.DeferredLifecycleHelper.a(Unknown Source:4)
        at com.huawei.hms.feature.dynamic.DeferredLifecycleHelper.onResume(Unknown Source:6)
        at com.huawei.hms.hmsscankit.RemoteView.onResume(RemoteView.java:1)
        at com.huawei.hms.hmsscankit.ScanKitActivity.onResume(ScanKitActivity.java:2)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7558)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4000)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4040) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7045) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
```

**Comment by nukc** [comment]
android.enableR8.libraries = false
android.enableR8 = false
关闭 R8 后，运行正常。

**Comment by nukc** [comment]
或者关闭混淆也正常
