### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by Godikov** [HMS-Core/hms-scan-demo#36]
java.lang.SecurityException
getNetworkTypeForSubscriber

com.huawei.hms.mlkit.common.ha.d.b(HianalyticsLogUtils.java:68)
最新版本Android11还是会报这个问题，而且是移动网络的时候会有，但是连接WIFI的时候不会。

**Comment by Godikov** [comment]
<html>
<body>


21206-30 10:31:59.507 5449 6575 E AndroidRuntime: java.lang.SecurityException: getNetworkTypeForSubscriber
--
21306-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.os.Parcel.createExceptionOrNull(Parcel.java:2384)
21406-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.os.Parcel.createException(Parcel.java:2368)
21506-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:2351)
21606-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:2293)
21706-30 10:31:59.507 5449 6575 E AndroidRuntime: at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8790)
21806-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3102)
21906-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3064)
22006-30 10:31:59.507 5449 6575 E AndroidRuntime: at com.huawei.hms.mlkit.common.ha.d.b(HianalyticsLogUtils.java:68)
22106-30 10:31:59.507 5449 6575 E AndroidRuntime: at com.huawei.hms.mlkit.common.ha.HianalyticsLogProvider.logEnd(HianalyticsLogProvider.java:6315)
22206-30 10:31:59.507 5449 6575 E AndroidRuntime: at com.huawei.hms.ml.camera.g$a.a(HiAnalyticsThread.java:109)
22306-30 10:31:59.507 5449 6575 E AndroidRuntime: at com.huawei.hms.ml.camera.g$a.handleMessage(HiAnalyticsThread.java:78)
22406-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:109)
22506-30 10:31:59.507 5449 6575 E AndroidRuntime: at android.os.Looper.loop(Looper.java:228)
22606-30 10:31:59.507 5449 6575 E AndroidRuntime: at com.huawei.hms.ml.camera.g.run(HiAnalyticsThread.java:51)
22706-30 10:31:59.508 5449 6575 E CrashReport: Java Crash Happen cause by Thread-23(3227)


</body>
</html>

**Comment by Mike-mei** [comment]
请问使用的测试机型是什么？目前使用scan哪个版本？

**Comment by Godikov** [comment]
NTH-AN00
com.huawei.hms:scanplus:1.3.2.300

**Comment by Godikov** [comment]
> 请问使用的测试机型是什么？目前使用scan哪个版本？

NTH-AN00
com.huawei.hms:scanplus:1.3.2.300

**Comment by Antine** [comment]
02-15 16:22:43.619  2997 13311 E HaLogProvider: GrsApi.synGetGrsUrl=https://metrics1.data.hicloud.com:6447,BuildConfig.HIA_MODE=com.huawei.cloud.mlkithianalytics
02-15 16:22:43.623  2997 13311 E HaLogProvider: forbiddenHiLog.getVenderCountry=cn
02-15 16:22:43.630  2997 13340 E [DETECT]: outputNum 0
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:ThreadName is Thread-39, pid is 2997 tid is 13311.
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:java.lang.SecurityException: getDataNetworkTypeForSubscriber
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.createExceptionOrNull(Parcel.java:2443)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.createException(Parcel.java:2427)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.readException(Parcel.java:2410)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.readException(Parcel.java:2352)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:9325)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3022)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2984)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.mlkit.common.ha.d.b(HianalyticsLogUtils.java:68)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.mlkit.common.ha.HianalyticsLogProvider.logEnd(HianalyticsLogProvider.java:6315)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.scankit.p.o$a.a(HiAnalyticsThread.java:7)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.scankit.p.o$a.handleMessage(HiAnalyticsThread.java:6)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Handler.dispatchMessage(Handler.java:117)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Looper.loopOnce(Looper.java:205)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at android.os.Looper.loop(Looper.java:293)
02-15 16:22:43.634  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.scankit.p.o.run(HiAnalyticsThread.java:3)
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:ThreadName is Thread-39, pid is 2997 tid is 13311.
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:java.lang.SecurityException: getDataNetworkTypeForSubscriber
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.createExceptionOrNull(Parcel.java:2443)
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.createException(Parcel.java:2427)
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.readException(Parcel.java:2410)
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:	at android.os.Parcel.readException(Parcel.java:2352)
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:9325)
02-15 16:22:43.636  2997 13311 E CallKitUI: CallKit:	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3022)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2984)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.mlkit.common.ha.d.b(HianalyticsLogUtils.java:68)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.mlkit.common.ha.HianalyticsLogProvider.logEnd(HianalyticsLogProvider.java:6315)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.scankit.p.o$a.a(HiAnalyticsThread.java:7)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.scankit.p.o$a.handleMessage(HiAnalyticsThread.java:6)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at android.os.Handler.dispatchMessage(Handler.java:117)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at android.os.Looper.loopOnce(Looper.java:205)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at android.os.Looper.loop(Looper.java:293)
02-15 16:22:43.637  2997 13311 E CallKitUI: CallKit:	at com.huawei.hms.scankit.p.o.run(HiAnalyticsThread.java:3)
02-15 16:22:43.637  2997 13311 E DEBUG   : encryptLog: false, zipCrashLog: false
02-15 16:22:43.638  2997 13311 E DEBUG   : begin to generate java report
02-15 16:22:43.646  2997 13311 E DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-15 16:22:43.647  2997 13311 E DEBUG   : Basic Information: 'pid: 2997/tid: 13311/time: 20230215162243'
02-15 16:22:43.647  2997 13311 E DEBUG   : Cpu Information: 'abi: arm64-v8a,armeabi-v7a,armeabi/processor: -/hardware: SM7325'
02-15 16:22:43.647  2997 13311 E DEBUG   : Mobile Information: 'model: ABR-AL60/version: 12/sdk: 31'
02-15 16:22:43.647  2997 13311 E DEBUG   : Build fingerprint: 'HUAWEI/ABR-AL60/HWABR-QL:12/HUAWEIABR-AL60/103.0.0.200C00:user/release-keys'
02-15 16:22:43.648  2997 13311 E DEBUG   : Runtime Information: 'start: 20230215154427/maxheap: 402653184/primaryabi: arm64-v8a/ground: fg'
02-15 16:22:43.648  2997 13311 E DEBUG   : Application Information: 'version: 4.1.9/subversion: release/buildseq: 38a67409/versioncode: 419'
02-15 16:22:43.648  2997 13311 E DEBUG   : CrashSDK Information: 'version: 3.3.2.2/nativeseq: 211215141717/javaseq: 211215141717/arch: arm64-v8a/target: release'
02-15 16:22:43.648  2997 13311 E DEBUG   : Report Name: 611b11c6e623447a332109ec_4.1.9_38a67409_ABR-AL60_12_167644706769841127_20230215162243_fg_java.log
02-15 16:22:43.648  2997 13311 E DEBUG   : UUID: c4bf8367-2c81-4798-81f5-53c56a6dda1b
02-15 16:22:43.648  2997 13311 E DEBUG   : Log Type: java
02-15 16:22:43.648  2997 13311 E DEBUG   : Activity: (none)
02-15 16:22:43.648  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.648  2997 13311 E DEBUG   : um_app_channel: huawei
02-15 16:22:43.648  2997 13311 E DEBUG   : um_os: android
02-15 16:22:43.648  2997 13311 E DEBUG   : um_crash_sdk_version: 1.7.0
02-15 16:22:43.648  2997 13311 E DEBUG   : um_app_carrier: 
02-15 16:22:43.648  2997 13311 E DEBUG   : um_access: 2G/3G
02-15 16:22:43.648  2997 13311 E DEBUG   : um_access_subtype: LTE
02-15 16:22:43.648  2997 13311 E DEBUG   : um_network_type: 0
02-15 16:22:43.648  2997 13311 E DEBUG   : others_OS: harmony
02-15 16:22:43.648  2997 13311 E DEBUG   : um_app_puid: 
02-15 16:22:43.648  2997 13311 E DEBUG   : um_app_provider: 
02-15 16:22:43.648  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.649  2997 13311 E DEBUG   : Process Name: 'com.yzn.doctor_hepler'
02-15 16:22:43.649  2997 13311 E DEBUG   : Thread Name: 'Thread-39'
02-15 16:22:43.649  2997 13311 E DEBUG   : Back traces starts.
02-15 16:22:43.649  2997 13311 E DEBUG   : java.lang.SecurityException: getDataNetworkTypeForSubscriber
02-15 16:22:43.649  2997 13311 E DEBUG   : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2443)
02-15 16:22:43.649  2997 13311 E DEBUG   : 	at android.os.Parcel.createException(Parcel.java:2427)
02-15 16:22:43.649  2997 13311 E DEBUG   : 	at android.os.Parcel.readException(Parcel.java:2410)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at android.os.Parcel.readException(Parcel.java:2352)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:9325)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3022)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2984)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at com.huawei.hms.mlkit.common.ha.d.b(HianalyticsLogUtils.java:68)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at com.huawei.hms.mlkit.common.ha.HianalyticsLogProvider.logEnd(HianalyticsLogProvider.java:6315)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at com.huawei.hms.scankit.p.o$a.a(HiAnalyticsThread.java:7)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at com.huawei.hms.scankit.p.o$a.handleMessage(HiAnalyticsThread.java:6)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at android.os.Handler.dispatchMessage(Handler.java:117)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at android.os.Looper.loopOnce(Looper.java:205)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at android.os.Looper.loop(Looper.java:293)
02-15 16:22:43.650  2997 13311 E DEBUG   : 	at com.huawei.hms.scankit.p.o.run(HiAnalyticsThread.java:3)
02-15 16:22:43.650  2997 13311 E DEBUG   : Back traces ends.
02-15 16:22:43.650  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.650  2997 13311 E DEBUG   : meminfo:
02-15 16:22:43.651  2997 13311 E DEBUG   : MemTotal:        7525728 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : MemFree:          108476 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : MemAvailable:    1912148 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Buffers:            3644 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Cached:          2120844 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : SwapCached:        49104 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Active:          2073928 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Inactive:        1430476 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Active(anon):    1243448 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Inactive(anon):   403296 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Active(file):     830480 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Inactive(file):  1027180 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Unevictable:      185108 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Mlocked:          184000 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : SwapTotal:       4194300 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : SwapFree:         641612 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : ZramUsed:        1028752 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Dirty:              1040 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Writeback:             0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : AnonPages:       1552872 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Mapped:          1049160 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Shmem:            108900 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : KReclaimable:     324100 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Slab:             739988 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : SReclaimable:     220592 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : SUnreclaim:       519396 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : KernelStack:      127584 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : PageTables:       169788 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : NFS_Unstable:          0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Bounce:                0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : WritebackTmp:          0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : CommitLimit:     7957164 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Committed_AS:   170494064 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmallocTotal:   262930368 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmallocUsed:       82904 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmallocChunk:          0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Percpu:      
02-15 16:22:43.651  2997 13311 E DEBUG   :      13472 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : HardwareCorrupted:     0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : CmaTotal:         450560 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : CmaFree:           20940 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : CmaUsed:           10316 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : IonTotalCache:     83420 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : IonTotalUsed:     604780 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : GpuTotalUsed:     458160 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : AshmemUsed:       101224 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : RsvTotalUsed:     723852 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : Protected:        153420 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.651  2997 13311 E DEBUG   : status:
02-15 16:22:43.651  2997 13311 E DEBUG   : Name:	n.doctor_hepler
02-15 16:22:43.651  2997 13311 E DEBUG   : Umask:	0077
02-15 16:22:43.651  2997 13311 E DEBUG   : State:	S (sleeping)
02-15 16:22:43.651  2997 13311 E DEBUG   : Tgid:	2997
02-15 16:22:43.651  2997 13311 E DEBUG   : Ngid:	0
02-15 16:22:43.651  2997 13311 E DEBUG   : Pid:	2997
02-15 16:22:43.651  2997 13311 E DEBUG   : PPid:	898
02-15 16:22:43.651  2997 13311 E DEBUG   : TracerPid:	0
02-15 16:22:43.651  2997 13311 E DEBUG   : Uid:	10242	10242	10242	10242
02-15 16:22:43.651  2997 13311 E DEBUG   : Gid:	10242	10242	10242	10242
02-15 16:22:43.651  2997 13311 E DEBUG   : FDSize:	512
02-15 16:22:43.651  2997 13311 E DEBUG   : Groups:	3001 3002 3003 9997 20242 50242 
02-15 16:22:43.651  2997 13311 E DEBUG   : VmPeak:	30267656 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmSize:	30224064 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmLck:	       0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmPin:	       0 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmHWM:	  330124 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmRSS:	  305600 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : RssAnon:	  131872 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : RssFile:	  171804 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : RssShmem:	    1924 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmData:	 1983432 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmStk:	    8192 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmExe:	      12 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmLib:	  286484 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmPTE:	    2588 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : VmSwap:	   72280 kB
02-15 16:22:43.651  2997 13311 E DEBUG   : CoreDumping:	0
02-15 16:22:43.651  2997 13311 E DEBUG   : THP_enabled:	0
02-15 16:22:43.651  2997 13311 E DEBUG   : Threads:	147
02-15 16:22:43.651  2997 13311 E DEBUG   : SigQ:	0/27608
02-15 16:22:43.651  2997 13311 E DEBUG   : SigPnd:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : ShdPnd:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : SigBlk:	0000000080001200
02-15 16:22:43.651  2997 13311 E DEBUG   : SigIgn:	0000000000000001
02-15 16:22:43.651  2997 13311 E DEBUG   : SigCgt:	0000006e4000dcfe
02-15 16:22:43.651  2997 13311 E DEBUG   : CapInh:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : CapPrm:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : CapEff:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : CapBnd:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : CapAmb:	0000000000000000
02-15 16:22:43.651  2997 13311 E DEBUG   : NoNewPrivs:	0
02-15 16:22:43.651  2997 13311 E DEBUG   : Seccomp:	2
02-15 16:22:43.651  2997 13311 E DEBUG   : Speculation_Store_Bypass:	thread vulnerable
02-15 16:22:43.651  2997 13311 E DEBUG   : Cpus_allowed:	ff
02-15 16:22:43.651  2997 13311 E DEBUG   : Cpus_allowed_list:	0-7
02-15 16:22:43.651  2997 13311 E DEBUG   : Mems_allowed:	1
02-15 16:22:43.651  2997 13311 E DEBUG   : Mems_allowed_list:	0
02-15 16:22:43.651  2997 13311 E DEBUG   : voluntary_ctxt_switches:	27274
02-15 16:22:43.651  2997 13311 E DEBUG   : nonvoluntary_ctxt_switches
02-15 16:22:43.651  2997 13311 E DEBUG   : 	2833
02-15 16:22:43.651  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.652  2997 13311 E DEBUG   : memory info:
02-15 16:22:43.652  2997 13311 E DEBUG   : JavaMax:    393216 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : JavaTotal:  36444 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : JavaFree:   1596 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : NativeHeap: 126204 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : NativeAllocated: 113154 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : NativeFree: 13049 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : availMem:   2229068 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : threshold:  221184 kB
02-15 16:22:43.652  2997 13311 E DEBUG   : lowMemory:  false
02-15 16:22:43.652  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.652  2997 13311 E DEBUG   : recent status:
02-15 16:22:43.652  2997 13311 E DEBUG   : last version: '4.1.9/release/38a67409'
02-15 16:22:43.652  2997 13311 E DEBUG   : dumping all threads: false
02-15 16:22:43.652  2997 13311 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
02-15 16:22:43.652  2997 13311 E DEBUG   : logcat:

**Comment by Antine** [comment]
使用扫描库出现的异常。
**设备信息：**
机型版本：ABR-AL60
渠道信息：huawei
CPU架构：arm64-v8a,armeabi-v7a,armeabi
前后台状态：前台
网络类型：4g
系统：HarmonyOS
系统版本：12

**库信息**
com.huawei.agconnect:agcp:1.6.1.300
com.huawei.hms:scanplus:2.7.0.302
com.huawei.hms:push:6.7.0.300
