### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by tianguo1314** [HMS-Core/hms-scan-demo#84]
java.lang.NegativeArraySizeException: -413100
        at com.huawei.hms.scankit.aiscan.common.r.b(PlanarYUVLuminanceSource.java:5)
        at com.huawei.hms.scankit.s.decode(IRemoteFrameDecoderDelegateImpl.java:10)
        at com.huawei.hms.hmsscankit.api.IRemoteFrameDecoderDelegate$Stub.onTransact(IRemoteFrameDecoderDelegate.java:10)
        at android.os.Binder.transact(Binder.java:921)
        at com.huawei.hms.hmsscankit.api.IRemoteFrameDecoderDelegate$Stub$Proxy.decode(IRemoteFrameDecoderDelegate.java:10)
        at com.huawei.hms.scankit.j.a(DecodeHandler.java:31)
        at com.huawei.hms.scankit.j.handleMessage(DecodeHandler.java:8)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at com.huawei.hms.scankit.m.run(DecodeThread.java:4)

**Comment by xuxiapu** [comment]
@tianguo1314 
尊敬的开发者您好，
麻烦确认下以下信息，以便于我们更好的定位问题所在。
1.SDK版本号是什么？
2.采用以下哪种扫码模式 ：Default View Mode、Customized View Mode、Bitmap Mode、MultiProcessor Mode。
3.是否能够复现？如何复现？
4.复现手机的型号、Android版本。

**Comment by tianguo1314** [comment]
SDK：31
扫码模式：应该是默认的
是否能复现：必现
华为手机  Android10

附件为代码

[ScanActivity.txt](https://github.com/HMS-Core/hms-scan-demo/files/10444248/ScanActivity.txt)

**Comment by xuxiapu** [comment]
@tianguo1314 您好，麻烦再提供一下完整的日志呢

**Comment by tianguo1314** [comment]
完整的日志
[logcat.docx](https://github.com/HMS-Core/hms-scan-demo/files/10445001/logcat.docx)
[Uploading logcat_1.txt…]()
[Uploading logcat_2.txt…]()
[logcat_3.txt](https://github.com/HMS-Core/hms-scan-demo/files/10445892/logcat_3.txt)
[logcat_4.txt](https://github.com/HMS-Core/hms-scan-demo/files/10445893/logcat_4.txt)
